### ISSUE TITLE
Disabled IdleTimeout test case in WebSocketServerTestCase

### ISSUE THREAD

**Issue by pubudu91** [wso2/transport-http#38]
**Description:**
The mentioned test case was disabled since it kept failing intermittently. Need to look into why it is happening and fix it and enable the test case again. 

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**
Irunika

**Affected Product Version:**
6.0.74-SNAPSHOT

**Comment by irunika** [comment]
This is already fixed with https://github.com/wso2/transport-http/pull/167
