### ISSUE TITLE
 transport-http-6.0.289 we can't disable unwanted TLS versions.

### ISSUE THREAD

**Issue by Gayanthakaushal** [wso2/transport-http#413]
**Description:**
In the transport-http-6.0.289 version, there is no option to disable unwanted TLS versions. 
In the transport-http-6.0.163 version, we can disable unwanted TLS by enabling only the wanted TLS values as follows of the particular profile deployment.yaml file under the listenerConfigurations section.
```
parameters:
        - name: "sslEnabledProtocols"
          value: "TLSv1.2"
```
Since it's a security level risk not able to limit the TLS versions, it is better to add this feature to the transport-http-6.0.289 version as well.

**Affected Product Version:**
APIM-Analytics-3.0.0

**Comment by dilini-muthumala** [comment]
Closing the issue as the fix is added in wso2/msf4j#578
